// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.gome.im.dispatcher.protobuf;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommonMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gomeplus.im.dispatcher.protobuf.CommonMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *请求类型(1:汇报资源  2:拉取资源)
     * </pre>
     *
     * <code>optional int32 requestType = 1;</code>
     */
    int getRequestType();

    /**
     * <pre>
     *服务器的ipPort  如:  "127.0.0.1:8001"
     * </pre>
     *
     * <code>optional string ipPort = 2;</code>
     */
    String getIpPort();
    /**
     * <pre>
     *服务器的ipPort  如:  "127.0.0.1:8001"
     * </pre>
     *
     * <code>optional string ipPort = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpPortBytes();

    /**
     * <pre>
     *是否发生变化(返回给客户端的状态,无变化时不需要关心，有变化时读取msg字段为更新后的服务器资源列表)
     * </pre>
     *
     * <code>optional bool isChange = 3;</code>
     */
    boolean getIsChange();

    /**
     * <pre>
     *json扩展协议内容(原来请求拉取JSON协议内容) 汇报时如:"{"type": 1,"ipPort": "127.0.0.1:88770","cmd": [123,456]}"  ;拉取时如:"{"type":2}"
     * </pre>
     *
     * <code>optional string msg = 4;</code>
     */
    String getMsg();
    /**
     * <pre>
     *json扩展协议内容(原来请求拉取JSON协议内容) 汇报时如:"{"type": 1,"ipPort": "127.0.0.1:88770","cmd": [123,456]}"  ;拉取时如:"{"type":2}"
     * </pre>
     *
     * <code>optional string msg = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code com.gomeplus.im.dispatcher.protobuf.CommonMsg}
   */
  public  static final class CommonMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gomeplus.im.dispatcher.protobuf.CommonMsg)
      CommonMsgOrBuilder {
    // Use CommonMsg.newBuilder() to construct.
    private CommonMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonMsg() {
      requestType_ = 0;
      ipPort_ = "";
      isChange_ = false;
      msg_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CommonMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              requestType_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              ipPort_ = s;
              break;
            }
            case 24: {

              isChange_ = input.readBool();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.CommonMsg.class, Msg.CommonMsg.Builder.class);
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private int requestType_;
    /**
     * <pre>
     *请求类型(1:汇报资源  2:拉取资源)
     * </pre>
     *
     * <code>optional int32 requestType = 1;</code>
     */
    public int getRequestType() {
      return requestType_;
    }

    public static final int IPPORT_FIELD_NUMBER = 2;
    private volatile Object ipPort_;
    /**
     * <pre>
     *服务器的ipPort  如:  "127.0.0.1:8001"
     * </pre>
     *
     * <code>optional string ipPort = 2;</code>
     */
    public String getIpPort() {
      Object ref = ipPort_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ipPort_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *服务器的ipPort  如:  "127.0.0.1:8001"
     * </pre>
     *
     * <code>optional string ipPort = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpPortBytes() {
      Object ref = ipPort_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ipPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISCHANGE_FIELD_NUMBER = 3;
    private boolean isChange_;
    /**
     * <pre>
     *是否发生变化(返回给客户端的状态,无变化时不需要关心，有变化时读取msg字段为更新后的服务器资源列表)
     * </pre>
     *
     * <code>optional bool isChange = 3;</code>
     */
    public boolean getIsChange() {
      return isChange_;
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private volatile Object msg_;
    /**
     * <pre>
     *json扩展协议内容(原来请求拉取JSON协议内容) 汇报时如:"{"type": 1,"ipPort": "127.0.0.1:88770","cmd": [123,456]}"  ;拉取时如:"{"type":2}"
     * </pre>
     *
     * <code>optional string msg = 4;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *json扩展协议内容(原来请求拉取JSON协议内容) 汇报时如:"{"type": 1,"ipPort": "127.0.0.1:88770","cmd": [123,456]}"  ;拉取时如:"{"type":2}"
     * </pre>
     *
     * <code>optional string msg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestType_ != 0) {
        output.writeInt32(1, requestType_);
      }
      if (!getIpPortBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ipPort_);
      }
      if (isChange_ != false) {
        output.writeBool(3, isChange_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, requestType_);
      }
      if (!getIpPortBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ipPort_);
      }
      if (isChange_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isChange_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Msg.CommonMsg)) {
        return super.equals(obj);
      }
      Msg.CommonMsg other = (Msg.CommonMsg) obj;

      boolean result = true;
      result = result && (getRequestType()
          == other.getRequestType());
      result = result && getIpPort()
          .equals(other.getIpPort());
      result = result && (getIsChange()
          == other.getIsChange());
      result = result && getMsg()
          .equals(other.getMsg());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestType();
      hash = (37 * hash) + IPPORT_FIELD_NUMBER;
      hash = (53 * hash) + getIpPort().hashCode();
      hash = (37 * hash) + ISCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsChange());
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Msg.CommonMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.CommonMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.CommonMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.CommonMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.CommonMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg.CommonMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg.CommonMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Msg.CommonMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg.CommonMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg.CommonMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Msg.CommonMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gomeplus.im.dispatcher.protobuf.CommonMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gomeplus.im.dispatcher.protobuf.CommonMsg)
        Msg.CommonMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.CommonMsg.class, Msg.CommonMsg.Builder.class);
      }

      // Construct using com.gomeplus.im.dispatcher.protobuf.Msg.CommonMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestType_ = 0;

        ipPort_ = "";

        isChange_ = false;

        msg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_descriptor;
      }

      public Msg.CommonMsg getDefaultInstanceForType() {
        return Msg.CommonMsg.getDefaultInstance();
      }

      public Msg.CommonMsg build() {
        Msg.CommonMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.CommonMsg buildPartial() {
        Msg.CommonMsg result = new Msg.CommonMsg(this);
        result.requestType_ = requestType_;
        result.ipPort_ = ipPort_;
        result.isChange_ = isChange_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.CommonMsg) {
          return mergeFrom((Msg.CommonMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.CommonMsg other) {
        if (other == Msg.CommonMsg.getDefaultInstance()) return this;
        if (other.getRequestType() != 0) {
          setRequestType(other.getRequestType());
        }
        if (!other.getIpPort().isEmpty()) {
          ipPort_ = other.ipPort_;
          onChanged();
        }
        if (other.getIsChange() != false) {
          setIsChange(other.getIsChange());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.CommonMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.CommonMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int requestType_ ;
      /**
       * <pre>
       *请求类型(1:汇报资源  2:拉取资源)
       * </pre>
       *
       * <code>optional int32 requestType = 1;</code>
       */
      public int getRequestType() {
        return requestType_;
      }
      /**
       * <pre>
       *请求类型(1:汇报资源  2:拉取资源)
       * </pre>
       *
       * <code>optional int32 requestType = 1;</code>
       */
      public Builder setRequestType(int value) {

        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求类型(1:汇报资源  2:拉取资源)
       * </pre>
       *
       * <code>optional int32 requestType = 1;</code>
       */
      public Builder clearRequestType() {

        requestType_ = 0;
        onChanged();
        return this;
      }

      private Object ipPort_ = "";
      /**
       * <pre>
       *服务器的ipPort  如:  "127.0.0.1:8001"
       * </pre>
       *
       * <code>optional string ipPort = 2;</code>
       */
      public String getIpPort() {
        Object ref = ipPort_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ipPort_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *服务器的ipPort  如:  "127.0.0.1:8001"
       * </pre>
       *
       * <code>optional string ipPort = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpPortBytes() {
        Object ref = ipPort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ipPort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *服务器的ipPort  如:  "127.0.0.1:8001"
       * </pre>
       *
       * <code>optional string ipPort = 2;</code>
       */
      public Builder setIpPort(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        ipPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器的ipPort  如:  "127.0.0.1:8001"
       * </pre>
       *
       * <code>optional string ipPort = 2;</code>
       */
      public Builder clearIpPort() {

        ipPort_ = getDefaultInstance().getIpPort();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器的ipPort  如:  "127.0.0.1:8001"
       * </pre>
       *
       * <code>optional string ipPort = 2;</code>
       */
      public Builder setIpPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        ipPort_ = value;
        onChanged();
        return this;
      }

      private boolean isChange_ ;
      /**
       * <pre>
       *是否发生变化(返回给客户端的状态,无变化时不需要关心，有变化时读取msg字段为更新后的服务器资源列表)
       * </pre>
       *
       * <code>optional bool isChange = 3;</code>
       */
      public boolean getIsChange() {
        return isChange_;
      }
      /**
       * <pre>
       *是否发生变化(返回给客户端的状态,无变化时不需要关心，有变化时读取msg字段为更新后的服务器资源列表)
       * </pre>
       *
       * <code>optional bool isChange = 3;</code>
       */
      public Builder setIsChange(boolean value) {

        isChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否发生变化(返回给客户端的状态,无变化时不需要关心，有变化时读取msg字段为更新后的服务器资源列表)
       * </pre>
       *
       * <code>optional bool isChange = 3;</code>
       */
      public Builder clearIsChange() {

        isChange_ = false;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <pre>
       *json扩展协议内容(原来请求拉取JSON协议内容) 汇报时如:"{"type": 1,"ipPort": "127.0.0.1:88770","cmd": [123,456]}"  ;拉取时如:"{"type":2}"
       * </pre>
       *
       * <code>optional string msg = 4;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *json扩展协议内容(原来请求拉取JSON协议内容) 汇报时如:"{"type": 1,"ipPort": "127.0.0.1:88770","cmd": [123,456]}"  ;拉取时如:"{"type":2}"
       * </pre>
       *
       * <code>optional string msg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *json扩展协议内容(原来请求拉取JSON协议内容) 汇报时如:"{"type": 1,"ipPort": "127.0.0.1:88770","cmd": [123,456]}"  ;拉取时如:"{"type":2}"
       * </pre>
       *
       * <code>optional string msg = 4;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *json扩展协议内容(原来请求拉取JSON协议内容) 汇报时如:"{"type": 1,"ipPort": "127.0.0.1:88770","cmd": [123,456]}"  ;拉取时如:"{"type":2}"
       * </pre>
       *
       * <code>optional string msg = 4;</code>
       */
      public Builder clearMsg() {

        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *json扩展协议内容(原来请求拉取JSON协议内容) 汇报时如:"{"type": 1,"ipPort": "127.0.0.1:88770","cmd": [123,456]}"  ;拉取时如:"{"type":2}"
       * </pre>
       *
       * <code>optional string msg = 4;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        msg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.gomeplus.im.dispatcher.protobuf.CommonMsg)
    }

    // @@protoc_insertion_point(class_scope:com.gomeplus.im.dispatcher.protobuf.CommonMsg)
    private static final Msg.CommonMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Msg.CommonMsg();
    }

    public static Msg.CommonMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommonMsg>
        PARSER = new com.google.protobuf.AbstractParser<CommonMsg>() {
      public CommonMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CommonMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CommonMsg> getParserForType() {
      return PARSER;
    }

    public Msg.CommonMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tmsg.proto\022#com.gomeplus.im.dispatcher." +
      "protobuf\"O\n\tCommonMsg\022\023\n\013requestType\030\001 \001" +
      "(\005\022\016\n\006ipPort\030\002 \001(\t\022\020\n\010isChange\030\003 \001(\010\022\013\n\003" +
      "msg\030\004 \001(\tB\002P\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomeplus_im_dispatcher_protobuf_CommonMsg_descriptor,
        new String[] { "RequestType", "IpPort", "IsChange", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
